# name = "[FULL_NAME]"
# username = "[USERNAME]"
Avatar = "https://moondeer.blog/uploads/2021/3014652aa8.jpg"
ProfileAvatar = "https://moondeer.blog/uploads/2021/d2728f1610.jpg"
Email = "moondeer@moondeer.blog"
BriefBio = """Creative nonfiction, art, poetry, apps, philosophy, \
              music, wood work, knots, political culture critiques \
              … some of the things I make."""