# name = "[FULL_NAME]"
# username = "[USERNAME]"
Avatar = "https://moondeer.blog/uploads/2021/3014652aa8.jpg"
ProfileAvatar = "https://moondeer.blog/uploads/2021/d2728f1610.jpg"
ProfileURL = "https://moondeer.blog/about/"
Email = "moondeer@moondeer.blog"
BriefBio = """Creative nonfiction, art, poetry, apps, philosophy, \
              music, wood work, knots, political culture critiques \
              … some of the things I make."""
AboutBio = """Northside Hospital baby proudly indoctrinated into \
              the radical left at the University of Georgia in the \
              Deep South where I received a BA in English and a BS \
              in CS."""