home = [
  "HTML",
  "RSS",
  "JSON",
  "RSD",
  "ArchiveHTML",
  "ArchiveJSON",
  "PhotosJSON",
  "PodcastXML",
  "PodcastJSON",
  "WebAppManifest"
]
page = [ "HTML" ]
section = [ "HTML" ]
taxonomy = [ "HTML", "RSS", "JSON" ]
taxonomyTerm = [ "HTML", "RSS", "JSON" ]