[RSS]
baseName = "feed"

[JSON]
baseName = "feed"

[RSD]
mediaType = "application/xml"
baseName = "rsd"
isPlainText = true
notAlternative = true

[ArchiveHTML]
mediaType = "text/html"
path = "archive"
baseName = "index"
isPlainText = false
notAlternative = true

[ArchiveJSON]
mediaType = "application/json"
path = "archive"
baseName = "index"
isPlainText = true
notAlternative = true

[PhotosHTML]
mediaType = "text/html"
path = "photos"
baseName = "index"
isPlainText = false
notAlternative = true

[PhotosJSON]
mediaType = "application/json"
path = "photos"
baseName = "index"
isPlainText = true
notAlternative = true

[PodcastXML]
mediaType = "application/rss+xml"
baseName = "podcast"
isPlainText = true
notAlternative = true

[PodcastJSON]
mediaType = "application/json"
baseName = "podcast"
isPlainText = true
notAlternative = true

[WebAppManifest]
mediaType = "application/manifest+json"
baseName = "manifest"
rel = "manifest"
isPlainText = true
isHTML = false
notAlternative = true