[WebAppManifest]
mediaType = "application/manifest+json"
baseName = "manifest"
rel = "manifest"
isPlainText = true
isHTML = false
notAlternative = true

[BrowserConfig]
mediaType = "application/xml"
baseName = "browserconfig"
isPlainText = true
isHTML = false
notAlternative = true
