description = "All the latest thoughts to fall out my head."

# [Author]
# Avatar = "https://moondeer.blog/uploads/2021/3014652aa8.jpg"
# ProfileAvatar = "https://moondeer.blog/uploads/2021/d2728f1610.jpg"
# Email = "moondeer@moondeer.blog"

[Theme]
ThemeVersion = "v136"
VisibleThemeVersion = "test"
TemplateComments = true
IncludeDisqus = true
IncludeConversation = true

[Theme.Date]
ShortNames = "Mon, 02 Jan 2006 15:04:05 -0700"
TimeDay = "3:04 PM, Jan 2"
DateTime = "2006-01-02 15:04:05 -0700"
Headline = "Jan 2, 2006"
ISO8601 = "2006-01-02T15:04:05-07:00"