description = "All the latest thoughts to fall out my head."
mailto_email = "moondeer@moondeer.blog"
profile_avatar = "https://moondeer.blog/uploads/2021/d2728f1610.jpg"

[Theme]
ThemeVersion = "v119"
VisibleThemeVersion = "test"
InjectionSiteComments = true
IncludeDisqus = true
IncludeConversation = true

[Theme.Date]
ShortNames = "Mon, 02 Jan 2006 15:04:05 -0700"
TimeDay = "3:04 PM, Jan 2"
DashDigits = "2006-01-02 15:04:05 -0700"