title = "[TITLE]"
baseURL = "[SCHEME]://[HOSTNAME]/"
rssLimit = 25
uglyURLs = false
enableRobotsTXT = true
languageCode = "[LANGUAGE]"
paginate = 25

[author]
name = "[FULL_NAME]"
avatar = "https://micro.blog/[USERNAME]/avatar.jpg"
username = "[USERNAME]"

[mediaTypes."application/json"]
suffixes = [ "json" ]

[outputFormats.RSS]
baseName = "feed"

[outputFormats.JSON]
baseName = "feed"

[outputFormats.RSD]
mediaType = "application/xml"
baseName = "rsd"
isPlainText = true
notAlternative = true

[outputFormats.ArchiveHTML]
mediaType = "text/html"
path = "archive"
baseName = "index"
isPlainText = false
notAlternative = true

[outputFormats.ArchiveJSON]
mediaType = "application/json"
path = "archive"
baseName = "index"
isPlainText = true
notAlternative = true

[outputFormats.PhotosHTML]
mediaType = "text/html"
path = "photos"
baseName = "index"
isPlainText = false
notAlternative = true

[outputFormats.PhotosJSON]
mediaType = "application/json"
path = "photos"
baseName = "index"
isPlainText = true
notAlternative = true

[outputFormats.PodcastXML]
mediaType = "application/rss+xml"
baseName = "podcast"
isPlainText = true
notAlternative = true

[outputFormats.PodcastJSON]
mediaType = "application/json"
baseName = "podcast"
isPlainText = true
notAlternative = true

[outputs]
home = [
  "HTML",
  "RSS",
  "JSON",
  "RSD",
  "ArchiveHTML",
  "ArchiveJSON",
  "PhotosJSON",
  "PodcastXML",
  "PodcastJSON"
]
page = [ "HTML" ]
section = [ "HTML" ]
taxonomy = [ "HTML", "RSS", "JSON" ]
taxonomyTerm = [ "HTML", "RSS", "JSON" ]

[taxonomies]
category = "categories"

[blackfriday]
fractions = false

[params]

TestingThisShitOut = "Yes, bitches!"
brief_bio = "[ITUNES_DESCRIPTION]"

description = "All the latest thoughts to fall out my head."


twitter_username = "[TWITTER_USERNAME]"
github_username = "[GITHUB_USERNAME]"
instagram_username = "[INSTAGRAM_USERNAME]"

mailto_email = "moondeer@moondeer.blog"

paginate = 25
paginate_categories = true
paginate_home = true
paginate_replies = false

profile_avatar = "https://moondeer.blog/uploads/2021/d2728f1610.jpg"

twitter_username = "moondeerdotblog"

itunes_description = "[ITUNES_DESCRIPTION]"
itunes_category = "[ITUNES_CATEGORY]"
itunes_subcategory = "[ITUNES_SUBCATEGORY]"
itunes_author = "[ITUNES_AUTHOR]"
itunes_email = "[ITUNES_EMAIL]"
itunes_cover = "[ITUNES_COVER]"

site_id = "[SITE_ID]"
theme_seconds = "0"

plugins_css = [ ]
plugins_js = [ ]
plugins_html = [ ]
